export let spanish =
    {
        "Home":"Inicio",
        "MyAccount":"Mi cuenta",
        "WatchLater":"Ver más tarde",
        "VideoOnDemand":"Vídeo a la carta",
        "Notifications":"Notificaciones",
        "History":"Historia",
        "AllCategories":"todas las categorias",
        "TVSeries":"Series de Televisión",
        "Movie":"Película",
        "Documentaries":"Documentales",
        "ViewAll":"Ver todos",
        "Rate":"puntuación",
        "Autoplay":"Auto-reproducción",
        "Related Videos":"Videos relacionados",
        "Play":"Tocar",
        "Director":"Director",
        "Writer":"Escritor",
        "About":"Sobre",
        "PrivacyPolicy":"Política de privacidad",
        "Term&Conditions":"Términos y condiciones",
        "Search":"Buscar",
        "Cancel":"Cancelar",
        "NoVideosAddedToWatchLaterYet":"No videos para ver más tarde",
        "Addyourfavoritevideostoaccessandwatcheasilywithoutanyhassles.":"Agregue sus videos favoritos para acceder y mirar fácilmente sin problemas.",
        "ExploreVideos":"Explora videos",
        "SayHelloToTheFutureofMobiletainment":"",

    }
